name: Recovery Build

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: 'Manifest URL'
        required: true
        default: 'https://github.com'
      MANIFEST_BRANCH:
        description: 'Manifest Branch'
        required: true
        default: 'twrp-11'
      DEVICE_TREE_URL:
        description: 'Odkaz na vas boot.img'
        required: true
        default: 'https://github.com/rominek75-boop/wp12-twrp-tree.git'
      DEVICE_PATH:
        description: 'Device Path'
        required: true
        default: 'device/oukitel/WP12'
      DEVICE_NAME:
        description: 'Device Name'
        required: true
        default: 'WP12'
      MAKEFILE_NAME:
        description: 'Makefile Name'
        required: true
        default: 'twrp_WP12'
      BUILD_TARGET:
        description: 'Build Target'
        required: true
        default: 'bootimage'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run TWRP Builder
        uses: NoahDomingues/Auto-TWRP-Builder@main
        with:
          MANIFEST_URL: ${{ github.event.inputs.MANIFEST_URL }}
          MANIFEST_BRANCH: ${{ github.event.inputs.MANIFEST_BRANCH }}
          DEVICE_TREE_URL: ${{ github.event.inputs.DEVICE_TREE_URL }}
          DEVICE_PATH: ${{ github.event.inputs.DEVICE_PATH }}
          DEVICE_NAME: ${{ github.event.inputs.DEVICE_NAME }}
          MAKEFILE_NAME: ${{ github.event.inputs.MAKEFILE_NAME }}
          BUILD_TARGET: ${{ github.event.inputs.BUILD_TARGET }}
